### ISSUE TITLE
multiple axes support

### ISSUE THREAD

**Issue by guido-altmann** [LayTec-AG/Plotly.Blazor#11]
Support of multiple axes is required.

**Comment by sean-mcleish** [comment]
Multiple axes are now supported. [Example](https://github.com/LayTec-AG/Plotly.Blazor/blob/develop/Plotly.Blazor.Examples/Pages/MultipleAxes.razor)

![grafik](https://user-images.githubusercontent.com/64470948/83347831-0d935480-a328-11ea-8757-bb7c01be0716.png)
