### ISSUE TITLE
Example of CandleStick chart?

### ISSUE THREAD

**Issue by artemiusgreat** [LayTec-AG/Plotly.Blazor#12]
Is there an example of how to create a candlestick chart? 

Specifically, this kind of chart. 
[https://plotly.com/javascript/candlestick-charts/](https://plotly.com/javascript/candlestick-charts/)

This is default example with Scatter type. 
```
PlotlyChart chart;
Plotly.Blazor.Config config = new Plotly.Blazor.Config();
Plotly.Blazor.Layout layout = new Plotly.Blazor.Layout();
List<Scatter> data = new List<Scatter>
{
  new Scatter
  {
    Name = "Trace1",
    Mode = ScatterMode.Lines
  }
};
```
If I try to use CandleStick or Box as a type, VS complains that CandleStick is a static class and cannot be used as a type. 
```
PlotlyChart chart;
Plotly.Blazor.Config config = new Plotly.Blazor.Config();
Plotly.Blazor.Layout layout = new Plotly.Blazor.Layout();
List<Plotly.Candlestick> data = new List<Plotly.Candlestick>
{
  new Plotly.Candlestick
  {
    Name = "Trace1",
    Mode = ScatterMode.Lines
  }
};
```

**Comment by sean-mcleish** [comment]
Hi Artemis,

currently only the scatter plot exists as a prototype. A full version will be released in the next days. For this purpose we implement a program that generates a blazor wrapper based on a schema and therefore covers all possible chart types. I estimate that we can expect a release candidate at the end of next week or at the beginning of June. More detailed examples and documentation will be released after that.
I will contact you as soon as I have more information.

Stay tuned!

Sean

**Comment by artemiusgreat** [comment]
Thanks. For now, I'm using this approach with JS interop... 
https://github.com/lqdev/Blazly

**Comment by sean-mcleish** [comment]
Hey @artemiusgreat ,

I have uploaded the initial state of Plotly.Blazor now! Also added an [example of a candlestick chart](https://github.com/LayTec-AG/Plotly.Blazor/blob/develop/Plotly.Blazor.Examples/Pages/CandleStick.razor), which is identical to [this](https://plotly.com/javascript/candlestick-charts/#simple-candlestick-chart) JavaScript example.

![grafik](https://user-images.githubusercontent.com/64470948/83347777-aecddb00-a327-11ea-81b0-de2e22df5222.png)

Have a nice weekend!
