### ISSUE TITLE
The case of two or more y values on same x axis it only shows values of latest one on dragging cursor on it

### ISSUE THREAD

**Issue by tahaAttique** [LayTec-AG/Plotly.Blazor#135]
Hi, I am using Plotly blazor. The problem I am facing is that, in the case where there are two or more y values on same x axis, on dragging on the point the animation shows only the values of the latest one. 

![image](https://user-images.githubusercontent.com/47359465/149725133-151ec50d-f967-4556-9195-1eebd41eaf1d.png)

Even if I drag on 100M y-axis point it still shows me the value animation of the one 8M. 

I wanted value animation of each point even on the same x axis. 

Help will be appreciated.

**Comment by sean-mcl** [comment]
Similar issue: #136 

I hope you find a workaround, as long as the feature has not yet been implemented.
