### ISSUE TITLE
In case of having two points on same x and y axis, I am unable to see both the points. 

### ISSUE THREAD

**Issue by tahaAttique** [LayTec-AG/Plotly.Blazor#136]
Hi,  I am using Plotly blazor. The problem I am facing is that, when there are two points with same x and y axis then how to show count on that point. 

Right now it shows one point on that x and y and I am unable to figure out how many points are there on same x and y. 

![image](https://user-images.githubusercontent.com/47359465/149726928-e44dba9c-bcb1-45b0-92dd-b2a3c1b23b2c.png)

In the above image there are two points on x-5000 and y-5000 but we are able to see only one. I wanted a way to show that there is two-points with the same values. I wanted something like when I hover on that point it shows me count (num of points with same x and y) as well.

**Comment by sean-mcl** [comment]
Hey @tahaAttique,

Plotly.Blazor is just a wrapper for the original plotly.js. There is already an [open issue](https://github.com/plotly/plotly.js/issues/4294 ) with your feature request.

I will close the ticket here for now, as it is not relevant to this wrapper.

Good luck!

Sean
