### ISSUE TITLE
Scatter trace line shape changes

### ISSUE THREAD

**Issue by AzureGulf** [LayTec-AG/Plotly.Blazor#137]
After adding an annotation and then extending a trace, the line shape (initially set to Spline) reverts to a straight line, as per the attached image. Any pointers appreciated (am using chart,React() within a Razor component).
![SplineLostWhenRefreshingAnnotations](https://user-images.githubusercontent.com/18535145/150111367-20bd9e1f-c654-4805-8a29-be77e6e85e30.png)

**Comment by sean-mcl** [comment]
Hey, can you provide a code example please? :)

**Comment by AzureGulf** [comment]
Hi Sean - pretty sure this was an error in my code (probably the way in which I was refreshing the Razor components), so apologise, code for this is no longer available. Still using Plotly, works fine... but I'm finding increased memory consumption (200+Gb) for relatively short plots (300-1,000 points) - again, probably my problem/Razor page updates in Blazor, etc...
