### ISSUE TITLE
Update to .NET 6

### ISSUE THREAD

**Issue by centreboard** [LayTec-AG/Plotly.Blazor#145]
The current version works fine with .NET 6, but it seems worth updating for a few reasons:

- The option I've outlined in #27 requires updates made to event handling in Blazor in .NET 6. 
- Dependabot is submitting pull requests to use version 6 nuget packages
- .NET 5 is [out of support](https://github.com/dotnet/core/blob/main/releases.md) on May 08, 2022

**Comment by sean-mcl** [comment]
Hey,

thanks for your help. I will take care of everything tomorrow and, if necessary, process the pull requests and bring the library up to date.

Best regards

Sean
