### ISSUE TITLE
Surface chart orientation resets on React()

### ISSUE THREAD

**Issue by waffleShirt** [LayTec-AG/Plotly.Blazor#146]
I'm wondering if it is possible to retain the viewport orientation for a Surface chart after calling React()? I make use of showing and hiding surfaces on a chart quite regularly, but having to manually reorient the chart to look at a particular location after hiding a surface and calling React() adds a lot of tedium. 

I looked at the chart, its layout, the scene owned by the layout, and the camera owned by the scene, to see if there was some way of pulling out the values for the rotation, zoom, etc, but did not find anything that could be used. 

If it's something that isn't currently possible, but could reasonably be implemented, let me know and I can look into creating a pull request.

**Comment by centreboard** [comment]
Does setting [UIRevision](https://plotly.com/javascript/uirevision/) either on the layout or trace help by preserving user interaction on properties that haven't been updated in code?
https://github.com/LayTec-AG/Plotly.Blazor/blob/1349c4abe9f3afb762e3c821ebebbdd0cacc1bed/Plotly.Blazor/Layout.cs#L632

**Comment by waffleShirt** [comment]
Thanks @centreboard, that is exactly what I needed!

Upon creating the surface chart I set `UiRevision = 1` on the Layout, and then following any React() call assigning the UiRevision to itself preserves the current view.
