### ISSUE TITLE
Logarithmic axis

### ISSUE THREAD

**Issue by erikthysell** [LayTec-AG/Plotly.Blazor#158]
I would love the possibility for using logarithmic axis like matplotlib/matlab's semilogx / semilogy / loglog functionality described [here ](https://plotly.com/python/log-plot/ )for plotly.
I have searched for it but it does not yet seem be there...
Anyway, thanks for the excellent package.

**Comment by sean-mcl** [comment]
That should be possible, like in this example https://plotly.com/javascript/log-plot/

**Comment by erikthysell** [comment]
@sean-mcl  - super, thanks a lot. Found it here:
```
new XAxis {
    Type = Plotly.Blazor.LayoutLib.XAxisLib.TypeEnum.Log
}
```
