### ISSUE TITLE
Add "plotly-basic.min.js" to the project.

### ISSUE THREAD

**Issue by IvanJosipovic** [LayTec-AG/Plotly.Blazor#212]
Currently, this NuGet package bundles the "plotly-latest.min.js", I would like to use the "plotly-basic.min.js" script as its much smaller in size.

**Comment by tibkiss** [comment]
Is it feasible to simply add plotly-latest.min.js (version matched to Plotly.Blazor's built-in version) to wwwroot and replace the javascript import to point to the minimal version?

**Comment by sean-mcl** [comment]
> Is it feasible to simply add plotly-latest.min.js (version matched to Plotly.Blazor's built-in version) to wwwroot and replace the javascript import to point to the minimal version?

Should be possible I guess

**Comment by tibkiss** [comment]
@sean-mcl : Thanks for the prompt reply.

The reason I asked, because I tried it out and seemed to work. 
Not sure about the internals of Plotly.Blazor which would make this transition unsafe. 

Would you consider this hack safe? :)

**Comment by sean-mcl** [comment]
> @sean-mcl : Thanks for the prompt reply.
> 
> The reason I asked, because I tried it out and seemed to work. Not sure about the internals of Plotly.Blazor which would make this transition unsafe.
> 
> Would you consider this hack safe? :)

Well, it is safe, as long as of course only what is available in the slimmed down version is used. That's why I don't have any concerns, as long as you know what you're doing. 😄

**Comment by tibkiss** [comment]
> > @sean-mcl : Thanks for the prompt reply.
> > The reason I asked, because I tried it out and seemed to work. Not sure about the internals of Plotly.Blazor which would make this transition unsafe.
> > Would you consider this hack safe? :)
> 
> Well, it is safe, as long as of course only what is available in the slimmed down version is used. That's why I don't have any concerns, as long as you know what you're doing. 😄

Thanks!

**Comment by sean-mcl** [comment]
https://github.com/LayTec-AG/Plotly.Blazor/pull/432 introduces a new property UseBasicVersion to the PlotlyChart-Component.

It will automatically lazy load the basic minified instead of the full version.
