### ISSUE TITLE
X-axis DateTime rounded to nearest second

### ISSUE THREAD

**Issue by RichardClinton1980** [LayTec-AG/Plotly.Blazor#259]
Hi, any idea on how to avoid rounding the x-values to the nearest second as this makes my scatterplot look quite weird?

![Plotly](https://user-images.githubusercontent.com/58848405/209138448-21665dfb-741a-4625-a0f8-56768f4508c5.png)

**Comment by RichardClinton1980** [comment]
Anyway, I found the cause of the problem using dotPeek decompiler. In your DateTimeConverter class, you use "yyyy-MM-dd HH:mm:ss" as format. I decompiled to intermediate language with ildasm.exe, changed it to "yyyy-MM-dd HH:mm:ss.fff", compiled the IL-file back to dll with ilasm.exe and works like a charm now:

![Plotly3](https://user-images.githubusercontent.com/58848405/209316297-8f06a3c1-a79a-4307-86e2-44bdab47acd7.png)

**Comment by ChristineChetty11** [comment]
Can you please show how to create a simple timeseries chart like this
