### ISSUE TITLE
ClickAction Not Triggering

### ISSUE THREAD

**Issue by acrow59** [LayTec-AG/Plotly.Blazor#269]
I have tried setting up the ClickAction event on multiple chart types and cannot get the event to invoke. Could we please get an example on how this parameter is meant to be implemented? I assumed it would be something like the following but have had no luck.

```
<PlotlyChart Id="TestId" Config="config" Layout="layout" Data="data" @ref="chart" ClickAction="PieClick"/>

public void PieClick(Object x, Object y)
{
  //Do something with x & y
}
```

**Comment by sean-mcl** [comment]
Should be similar to the hover event.
See
Plotly.Blazor.Examples/Components/Hover.razor

You create a reference to the chart using @ref and then call the subscribe method. You can use the AfterRender-Method, provided by the chart component, to subscribe after the chart has been rendered.

I think the return type of the values (X and Y) is JsonElement, so you have to parse it too.

In my opinion, the event mechanism and return values should be overhauled and extended to all/more event arguments.

**Comment by acrow59** [comment]
Ahh, thank you! I was just missing the subscribe event. Seems to work fine for the Scatter graph, but for the Pie chart it returns null for both X and Y values. I also tried implementing the Hover event for Pie Chart to see if I could get the selected piece that way, but it's also just returning null for both X and Y values. Do you know of a way to retrieve which specific slice of the pie chart has been clicked?

**Comment by acrow59** [comment]
It looks like the issue is with how the plotly-interop.js is setup. It's currently designed to only return data with an X and Y value, so for charts like Pie that instead use Value and Label, it will always return null. I've created a PR to address this. With it, both Click and Hover events will return the Value/Label instead if X/Y data is not present.

PR: [https://github.com/LayTec-AG/Plotly.Blazor/pull/270](https://github.com/LayTec-AG/Plotly.Blazor/pull/270)

**Comment by sean-mcl** [comment]
Thanks for your contribution! 
Will create a new release in the next hour, have to update several dependencies first.

**Comment by sean-mcl** [comment]
Released.
