### ISSUE TITLE
Add offset by X, not only by Y

### ISSUE THREAD

**Issue by georgevangelou** [LayTec-AG/Plotly.Blazor#294]
Hi all!

I trying to create a graph resembling a Gantt chart. Because of that, I need to create bars horizontally. Sometimes, these bars need to have offsets in the X axis, which I see is not supported by the library.

I will show a simple example:

![image](https://user-images.githubusercontent.com/17727411/223773696-7fc7aa7a-ae99-4df7-827d-a9b85e7492c4.png)

I want to force Bar 2 to start somewhere above in the middle of Bar 1. I have defined the following traces:

![image](https://user-images.githubusercontent.com/17727411/223773952-b09070e6-744b-4bca-82de-463ae9b1ee43.png)

Of course, I have commented `Offset = 1`, since this moves the bar in the Y direction and not in the X, as I intend it to move.

Is there a way to have a X offset? Could this be implemented as a feature? Do you have any alternatives?

**Comment by sean-mcl** [comment]
Mhm, what happens when you add the offset to the X values directly. Like `X = new List<object> {1, 3}`

**Comment by sean-mcl** [comment]
Found it, the property that you look for is "Base = 1"
