### ISSUE TITLE
RelayoutEventData error with Date Xaxis

### ISSUE THREAD

**Issue by jsneedles** [LayTec-AG/Plotly.Blazor#369]
Hi, 

When using the `RelayoutAction` callback with an XAxis defined as `Type = TypeEnum.Date` and `SubscribeRelayoutEvent()` after Render, you get a deserialization error: 

`
Uncaught (in promise) Error: Unhandled Promise Rejection: System.Text.Json.JsonException: The JSON value could not be converted to System.Double. Path: $.XRange[0] | LineNumber: 0 | BytePositionInLine: 37.
`

I believe the `PlotlyRelayoutEventData.XRange` should be `object[]` instead of `double[]`

Thanks for the awesome library!

**Comment by jsneedles** [comment]
Oh! 
Just saw #302 - that should fix this.

Any chance that could come soon, now that 3.0 is out?

**Comment by sean-mcl** [comment]
> Oh! Just saw #302 - that should fix this.
> 
> Any chance that could come soon, now that 3.0 is out?

Yeah it’s okay I guess. Will merge the conflict tomorrow. 😅

**Comment by sean-mcl** [comment]
Done.
