### ISSUE TITLE
Correct Implementation of X-Axis RangeSlider

### ISSUE THREAD

**Issue by mg-yolo-enterprises** [LayTec-AG/Plotly.Blazor#383]
I couldn't find an example for coding up an x-axis RangeSlider, which is really handy addition to any large time series scatter chart.

With a little trial and error (and some experience with Plotly.NET) I was able to get it working with 
`Layout layout = new(){XAxis = new List<XAxis>{new(){RangeSlider = new RangeSlider()}}};`

And I just wanted to verify this was the correct way to do this.

**Comment by sean-mcl** [comment]
Yes, thats correct.  👍🏻
