### ISSUE TITLE
Click event doesn't work for heatmaps.

### ISSUE THREAD

**Issue by BrockLeeBytes** [LayTec-AG/Plotly.Blazor#414]
The `PointNumber` property in `EventDataPoint` is returned as an array when a heat map cell is clicked on. This causes an json parsing error on the client side and the C# click event never actually activates.

I was able to fix this issue relatively easily by adding the Plotly.Blazor source code to my project and changing `PointIndex` from an `int` to an `object`.

**Comment by sean-mcl** [comment]
Okay, will probably be a breaking change.
Will check it out next week, too.

**Comment by sean-mcl** [comment]
Integrated in #433
