### ISSUE TITLE
4.3.0 + plotly-basic-latest.min.js

### ISSUE THREAD

**Issue by ClashOfStyles** [LayTec-AG/Plotly.Blazor#427]
Is there a way to use [plotly-basic-latest.min.js](https://cdn.plot.ly/plotly-basic-latest.min.js) with Ploty.Blazor version 4.3.0?

**Comment by sean-mcl** [comment]
Will check it out next week. :)

**Comment by sean-mcl** [comment]
https://github.com/LayTec-AG/Plotly.Blazor/pull/432 introduces a new property `UseBasicVersion` to the PlotlyChart-Component.

It will automatically lazy load the basic minified instead of the full version.
