### ISSUE TITLE
Version 5.1.1 reports plotly-latest.min.js MIME type as text/html instead of text/javascript

### ISSUE THREAD

**Issue by mmauri** [LayTec-AG/Plotly.Blazor#440]
Hi,
Thank you for your work on the plotly wrapper,
This is what v.4.3.0 shows (correct):
![image](https://github.com/user-attachments/assets/e14478d6-e3e9-4731-a02c-e10bd3dcf840)

But 5.1.1 reports MIME type as text/html:
![image](https://github.com/user-attachments/assets/e366b550-fd1d-4f3e-aca0-90c8ac72aa2a)

The tricky point is that if the content-security-policy is enabled, Chromium refuses to load the plotly.js:
![image](https://github.com/user-attachments/assets/c8989fae-8a14-4b3c-9aee-6f52abf63567)

Thanks
M

**Comment by mmauri** [comment]
It was much simpler, the new version does not copy the plotly.js as stated in the docs-> plotly-latest.min.js
Instead just copies with the version name, so the script link has to be updated
![image](https://github.com/user-attachments/assets/2a160cbf-b0bc-4348-a0ad-5d03a7429e82)

**Comment by sean-mcl** [comment]
Usually you don't have to import these files anymore in the Index.html, Plotly.Blazor loads it on its own dynamically.
