### ISSUE TITLE
Help, how do I ensure that a combo line and bar chart's y axis both align on zero?

### ISSUE THREAD

**Issue by iancoetzer** [LayTec-AG/Plotly.Blazor#450]
What I mean is that I am seeing this and do not know how to make sure both zero - they both start with same x value and y value of zero (0)?

but it looks like this:

![image](https://github.com/user-attachments/assets/ac09dcae-1f63-4475-901c-c8d795418f32)

I want to see it like this! by default

![image](https://github.com/user-attachments/assets/705c9bca-32de-4369-b10e-108cd840c955)

**Comment by iancoetzer** [comment]
Hi, I may have pasted this in the incorrect section.
Apologies, I just need an example of how to do this, I doubt it is an error in the current distribution.

**Comment by sean-mcl** [comment]
> Hi, I may have pasted this in the incorrect section. Apologies, I just need an example of how to do this, I doubt it is an error in the current distribution.

You can try to set the Range in the axis definition. Or the RangeMode to „ToZero“

**Comment by iancoetzer** [comment]
Hi, Thank you for the tip, closer after setting RangeMode to **RangeModeEnum.Normal**: but still not perfect:

![image](https://github.com/user-attachments/assets/1ad2234f-ad55-4181-a6d6-7ac4dbdfcadf)

If I set it to **RangeModeEnum.ToZero** it looks worse: How can I ensure that both -10's are on the same horizontal level, I did make sure both start at minimum value that is the minimum of both's starting points


![image](https://github.com/user-attachments/assets/4b9bcafa-6a36-4dea-9fa8-4cc0a7e183f4)

**Comment by sean-mcl** [comment]
Do you have "overlaying: 'y'" for the 2nd y axis?
