### ISSUE TITLE
Help with HoverTemplate

### ISSUE THREAD

**Issue by ppvario** [LayTec-AG/Plotly.Blazor#456]
Hello,
I was wondering if there is any way to set the locale using the HoverTemplate property?

I want to represent numbers in two languages: English and German
For eg: 1.268 in english would be 1,268 in german.

I tried to find something on https://d3js.org/d3-format#locale_format but that requires javascript, It would be great if there was an option to do that directly in HoverTemplate

Edit: I scrapped the initial idea of using HoverTemplate, as its just a string and does not allow any modifications by default. I tried to manually add a javascript function that is triggered everytime the HoverAction is triggered. I wrote the logic of converting the english format to german inside that function. It worked but not as I expected. Some numbers were still shown in the english format. Upon investigating I came to know that the formating was reverted (sometimes) due to the tooltip component being re-rendered by ploty.js. 
I am not sure how to work around this issue. Can you help?

**Comment by sean-mcl** [comment]
Maybe you want to check this out:

https://github.com/plotly/plotly.js/tree/master/dist#to-include-localization

**Comment by Apflkuacha** [comment]
I was looking for how to change the localisation texts directly in .NET, here the information on how to do it: the locale could be set with `config.Locale = "de";` that is easy. And here the more complex info how to change the texts: 

    config.Locales = new {
        de = new
        {
            dictionary = new Dictionary<string, string> { { "Autoscale", "Automatische Skalierung" }, { "Zoom in", "Hineinzoomen" }, { "Zoom out", "Herauszoomen" }, } },
            format = new
            {
                days = new string[] { "Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag" },
                shortDays = new string[] { "So", "Mo", "Di", "Mi", "Do", "Fr", "Sa" },
                months = new string[] { "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" },
                shortMonths = new string[] { "Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez" },
                date = "%d.%m.%Y",
            }
        }
    };

The description on the property Locales is not that clear how the objects should be set, now it is documented at least here.
