### ISSUE TITLE
Difference in debug mode and build

### ISSUE THREAD

**Issue by HansenBerlin** [LayTec-AG/Plotly.Blazor#54]
I am using your repo as a base for a dashboard like website thats supposed to run only locally. I did not change anything in the structure. When I run the app in debug mode right out of VS, either IIS or just the examples project it all works fine, renders, all graphs are shown, no errors etc. I do have some warning because async methods crash some of the graphs but for a local environment sync methods should work fine I guess.
So when building the app, starting the exe and calling localhost in the browser, the app gets rendered partly, graphs are not rendered at all and when chanhing sites via the menu it crashes. Seems to be an issue with java interop, I paste the error and warnings from the console here.
If you have any idea what this is about I'd be happy about your answer. I have intermediate experience with c# but almost none in blazor yet.

Debug from visual studio
![grafik](https://user-images.githubusercontent.com/42807459/98236053-0588b200-1f63-11eb-982f-669303160770.png)

Debug or Release from build folder:
![grafik](https://user-images.githubusercontent.com/42807459/98236217-47b1f380-1f63-11eb-92c1-a11d2842085a.png)

Errors/Warnings when running from Debug/Release:
![grafik](https://user-images.githubusercontent.com/42807459/98236444-a5464000-1f63-11eb-9aea-5148af47cd1d.png)

**Comment by EuanKirkhope** [comment]
I run in the same way, local exe and mainly localhost web serving. 

I suspect your problem is that the js files are not in the right folder for your release build.  I had to manually move some js files around to be in _content folder and fix the references in the project.

If you open the inspect window in chrome it will tell you in the console what the main errors are.  Lost likely missing js files.

Regards,

Euan

**Comment by sean-mcleish** [comment]
Hi,

looks like `_content/Plotly.Blazor/plotly-interop.js` is missing in the output path.
This file is normally delivered with the NuGet package and is automatically stored under this path

Could you please show me your Index.html?

Greetings,

Sean

**Comment by HansenBerlin** [comment]
Hey, it worked fine now. I added the dependencies in the csproject file and now its working fine! Thanks for the quick response.

**Comment by sean-mcleish** [comment]
Nice. And thanks also to @EuanKirkhope for the quick answer. :)
