### ISSUE TITLE
Cannot successfully install version 2.0.0

### ISSUE THREAD

**Issue by Varunda** [LayTec-AG/Plotly.Blazor#76]
When I install the 2.0.0 version of the package, there is no `Plotly` namespace that can be imported. 

Steps to recreate:
1. Install Plotly.Blazor: `dotnet add package Plotly.Blazor --version 2.0.0`
2. Add imports in _Imports: `@using Plotly.Blazor`

Attempting to compile will say `The type or namespace name Plotly could not be found`

Instead installing version 1.5.0 will fix this issue.
1. Install Plotly.Blazor: `dotnet add package Plotly.Blazor --version 1.5.0`
2. Add imports: `@using Plotly.Blazor`

Import will work successfully

**Comment by sean-mcl** [comment]
Plotly.Blazor > 2.0.0 only supports .NET 5 and higher.
