### ISSUE TITLE
Refresh Pie or Bar charts

### ISSUE THREAD

**Issue by gtejeda** [LayTec-AG/Plotly.Blazor#85]
Thanks for this contribution guys, It's working beautifully!

However, when I update the parameters, I new up a new list<itrace> and re-calculate the data, however the chart doesn't refresh...
I tried by calling the chart.React method and still can't get it to update.

Do you have any ideas of what it could be?

**Comment by sean-mcl** [comment]
Hi, do you have a working example? :)

**Comment by gtejeda** [comment]
Greetings Sean, I don't have the code online, so I hope this video explanation of the problem could help determine the issue:
https://gtejeda.tinytake.com/tt/NTQzMDQyOV8xNjk4NDE0NA

And this is the code for loading the pie char:
`public async Task GetMessages()
    {
        if (Messages != null && Messages.Count > 0)
        {
            data = new List<ITrace>();
            totalMessages = Messages.Count;
            var channels = Messages.Select(x => x.Channel.ToString()).Distinct();

            var channelList = new List<object>(channels);
            var messagesList = new List<object>();

            foreach (var channel in channels)
            {
                var messagesPerChannel = Messages.Count(x => x.Channel.ToString() == channel);
                messagesList.Add(messagesPerChannel);
            }

            data.Add(new Pie() { Values = messagesList, Labels = channelList });

            if (chart != null)
            {
                await chart.React();
            }

            StateHasChanged();
        }
    }`

The Bar chart is virtually the same code... any idea would be super greatly appreciated of course.

**Comment by riboyama** [comment]
So you add a `new Pie()` to your `IList<ITrace> data`? If you want to update your chart you need to either replace or append the Values and Labels to that specific `Pie()`. See below method that I use for initial loading, and replacing data:
```    
public void SetDataSet(List<object> labels, List<object> values)
    {
        if (values.Count == 0) return;
        if (_chart.Data.FirstOrDefault() is not Pie pie) return;
        pie.Values = values;
        pie.Labels = labels;
        _chart.React();
    }
```

**Comment by gtejeda** [comment]
It works BEAUTIFULLY for the pie... 

Could I trouble you for a similar snippet for the Bar chart?
I tried to use the same technique, but considering the multiple Y points, I coudn't figure out how to properly applied it.

I thought I could simply chart.Data.RemoveAt(0); and fill it anew, but that didn't work.
Thanks a million!

**Comment by sean-mcl** [comment]
> So you add a `new Pie()` to your `IList<ITrace> data`? If you want to update your chart you need to either replace or append the Values and Labels to that specific `Pie()`. See below method that I use for initial loading, and replacing data:
> 
> ```
> public void SetDataSet(List<object> labels, List<object> values)
>     {
>         if (values.Count == 0) return;
>         if (_chart.Data.FirstOrDefault() is not Pie pie) return;
>         pie.Values = values;
>         pie.Labels = labels;
>         _chart.React();
>     }
> ```

Thank you for helping, appreciate it :)

**Comment by riboyama** [comment]
> 
> 
> It works BEAUTIFULLY for the pie...
> 
> Could I trouble you for a similar snippet for the Bar chart?
> I tried to use the same technique, but considering the multiple Y points, I coudn't figure out how to properly applied it.
> 
> I thought I could simply chart.Data.RemoveAt(0); and fill it anew, but that didn't work.
> Thanks a million!

```
    public void SetDataSet(List<object> x, List<object> y)
    {
        if (_chart.Data.FirstOrDefault() is not Bar bar) return;
        bar.X = x;
        bar.Y = y;
        _chart.React();
    }
```

**Comment by LucaZiegler** [comment]
Got the same issue with Candlesticks, got it working by adding _chart.React()
